version: "3"  # optional since v1.27.0
services:
  app:
    build:
      context: .
      dockerfile: ./cmd/app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/go/src/example/
    restart: always

